name: Update README.md
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
  schedule:
    - cron: "0 */12 * * *"
jobs:
 update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name nellsavedra
          git config user.email nellsavedra@gmail.com
          date >> .log
          git add .
          git commit -m "Update README.md"
          git push origin main
